name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 6b9f937475db9280d966f44f469bc80191b5092a

    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get demo-libs
      run: sudo apt-get install -y --no-install-recommends liballegro5-dev liballegro-image5-dev liballegro-ttf5-dev libglfw3 libglfw3-dev libglew-dev libsdl2-dev libwayland-dev libx11-dev libxft-dev wayland-protocols
    - name: build all makefiles
      run: |
        find . -name Makefile | while read makefile; do
          dir=$(dirname "$makefile")
          echo "Entering directory: $dir"
          (cd "$dir" && make)
        done
